[tool.poetry]
name = "mongo2pq"
version = "0.1.0"
description = "Script to extract collections from MongoDB and load it to Parquet"
authors = ["Tadeas Uhlir <tadeas.uhlir@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pymongo = "^4.18.2"
pyarrow = "^20.0.0"
motor = "^3.7.1"
tqdm = "^4.67.1"
pyyaml = "^6.0.2"

[tool.poetry.group.dev.dependencies]
ipython = "^9.3.0"

[tool.poetry.scripts]
mongo2pq = 'mongo2pq.main:run'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
